### ISSUE TITLE
A-Softmax

### ISSUE THREAD

**Issue by bonseyes-admin** [binLearning/caffe-tea#1]
Have you considered adding this loss?

[](https://arxiv.org/pdf/1704.08063)

https://github.com/wy1iu/sphereface/blob/master/tools/caffe-sphereface/src/caffe/layers/margin_inner_product_layer.cpp

**Comment by binLearning** [comment]
I recently had some work to deal with, might not have added this loss in the near future. But later I will add more functions, such as A-Softmax, FN(Feature Normalization), etc.
FN is proposed in [DeepVisage: Making face recognition simple yet with powerful generalization skills](https://arxiv.org/abs/1703.08388)
